### NumPy

In [1]:
import numpy as np

In [2]:
l = ['aziart',1,2,3,4]
type(l)

list

In [3]:
np.array(l)

array(['aziart', '1', '2', '3', '4'], dtype='<U21')

n-dimensional array

In [4]:
type(np.array(l))

numpy.ndarray

numpy.array tries to upcast its elements. Example:

In [5]:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [6]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
a[1]

array([3, 4])

In [9]:
a[1][1]

4

In [10]:
a[1,1]

4

In [11]:
a1 = np.array([1,2,3,4,5.0])
a1

array([1., 2., 3., 4., 5.])

In [12]:
a1[3]

4.0

In [13]:
np.array([1,2,3,4,5,6], ndmin=0)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.array([1,2,3,4,5,6], ndmin=1)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.array([1,2,3,4,5,6], ndmin=2)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
dim_3 = np.array([1,2,3,4,5,6], ndmin=3)
dim_3

array([[[1, 2, 3, 4, 5, 6]]])

In [17]:
dim_3[0][0][3]

4

In [18]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [19]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [21]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [22]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [23]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [24]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [36]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i, j: i==j, (3,8))

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False]])

In [38]:
np.fromfunction((lambda i, j: i*j), (4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.]])

In [41]:
np.fromfunction((lambda i, j: i*j), (4,5), dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [42]:
np.mat(np.fromfunction((lambda i, j: i*j), (4,5), dtype=int))

matrix([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]])

In [44]:
np.fromfunction((lambda i, j, z: i*j*z), (1,2,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]]])

In [47]:
np.fromfunction((lambda i, j, z: i+j+z), (1,3,6), dtype=int)

array([[[0, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7]]])

In [49]:
np.fromfunction((lambda i, j, z: i+j+z), (2,4,6), dtype=int)
# 2 matrices
# 4 rows and 6 columns

array([[[0, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7, 8],
        [4, 5, 6, 7, 8, 9]]])

In [69]:
np.fromfunction((lambda i, j, a, b: i+j+a+b), (3,2,1,5), dtype=int)
# 3 such arrays where
# every array has 2 such matrices where
# there are 1 row and 5 columns

array([[[[0, 1, 2, 3, 4]],

        [[1, 2, 3, 4, 5]]],


       [[[1, 2, 3, 4, 5]],

        [[2, 3, 4, 5, 6]]],


       [[[2, 3, 4, 5, 6]],

        [[3, 4, 5, 6, 7]]]])