### NumPy

In [1]:
import numpy as np

In [2]:
l = ['aziart',1,2,3,4]
type(l)

list

In [3]:
np.array(l)

array(['aziart', '1', '2', '3', '4'], dtype='<U21')

n-dimensional array

In [4]:
type(np.array(l))

numpy.ndarray

numpy.array tries to upcast its elements. Example:

In [5]:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [6]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
a[1]

array([3, 4])

In [9]:
a[1][1]

4

In [10]:
a[1,1]

4

In [11]:
a1 = np.array([1,2,3,4,5.0])
a1

array([1., 2., 3., 4., 5.])

In [12]:
a1[3]

4.0

In [13]:
np.array([1,2,3,4,5,6], ndmin=0)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.array([1,2,3,4,5,6], ndmin=1)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.array([1,2,3,4,5,6], ndmin=2)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
dim_3 = np.array([1,2,3,4,5,6], ndmin=3)
dim_3

array([[[1, 2, 3, 4, 5, 6]]])

In [17]:
dim_3[0][0][3]

4

In [18]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [19]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [21]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [22]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [23]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [24]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [25]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i, j: i==j, (3,8))

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False]])

In [27]:
np.fromfunction((lambda i, j: i*j), (4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.]])

In [28]:
np.fromfunction((lambda i, j: i*j), (4,5), dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [29]:
np.mat(np.fromfunction((lambda i, j: i*j), (4,5), dtype=int))

matrix([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]])

In [30]:
np.fromfunction((lambda i, j, z: i*j*z), (1,2,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]]])

In [31]:
np.fromfunction((lambda i, j, z: i+j+z), (1,3,6), dtype=int)

array([[[0, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7]]])

In [32]:
np.fromfunction((lambda i, j, z: i+j+z), (2,4,6), dtype=int)
# 2 matrices
# 4 rows and 6 columns

array([[[0, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7, 8],
        [4, 5, 6, 7, 8, 9]]])

In [33]:
np.fromfunction((lambda i, j, a, b: i+j+a+b), (3,2,1,5), dtype=int)
# 3 such arrays where
# every array has 2 such matrices where
# there are 1 row and 5 columns

array([[[[0, 1, 2, 3, 4]],

        [[1, 2, 3, 4, 5]]],


       [[[1, 2, 3, 4, 5]],

        [[2, 3, 4, 5, 6]]],


       [[[2, 3, 4, 5, 6]],

        [[3, 4, 5, 6, 7]]]])

In [34]:
a = np.fromfunction((lambda i, j, k: i*j*k), (4,3,2), dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [35]:
a.ndim

3

In [36]:
a.size

24

In [37]:
a.shape

(4, 3, 2)

In [38]:
a.dtype

dtype('int64')

In [39]:
a = np.fromfunction((lambda i, j: i*j), (10,20), dtype=int)
a

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42,  45,  48,  51,  54,  57],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60,  64,  68,  72,  76],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70,  75,  80,  85,  90,  95],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
         78,  84,  90,  96, 102, 108, 114],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105, 112, 119, 126, 133],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  

In [40]:
import pandas as pd

In [41]:
pd.DataFrame(a)

0   1   2   3   4   5   6   7   8   9   10  11   12   13   14   15   16  \
0   0   0   0   0   0   0   0   0   0   0   0   0    0    0    0    0    0   
1   0   1   2   3   4   5   6   7   8   9  10  11   12   13   14   15   16   
2   0   2   4   6   8  10  12  14  16  18  20  22   24   26   28   30   32   
3   0   3   6   9  12  15  18  21  24  27  30  33   36   39   42   45   48   
4   0   4   8  12  16  20  24  28  32  36  40  44   48   52   56   60   64   
5   0   5  10  15  20  25  30  35  40  45  50  55   60   65   70   75   80   
6   0   6  12  18  24  30  36  42  48  54  60  66   72   78   84   90   96   
7   0   7  14  21  28  35  42  49  56  63  70  77   84   91   98  105  112   
8   0   8  16  24  32  40  48  56  64  72  80  88   96  104  112  120  128   
9   0   9  18  27  36  45  54  63  72  81  90  99  108  117  126  135  144   

    17   18   19  
0    0    0    0  
1   17   18   19  
2   34   36   38  
3   51   54   57  
4   68   72   76  
5   85   90   95  
6  102  108  114  
7  119  126  133  
8  136  144  152  
9  153  162  171

In [42]:
np.random.rand(10,4)

array([[0.84049784, 0.53168159, 0.68255238, 0.54471928],
       [0.88221575, 0.70842613, 0.25720216, 0.88616513],
       [0.00917051, 0.6411612 , 0.39488001, 0.17577931],
       [0.3751557 , 0.29648103, 0.87934615, 0.14736191],
       [0.78311366, 0.96536756, 0.21847542, 0.52165474],
       [0.08644999, 0.68311363, 0.69172289, 0.03374832],
       [0.73899306, 0.83302828, 0.42608579, 0.03312029],
       [0.31658436, 0.79747143, 0.38087622, 0.20061874],
       [0.98603323, 0.3401822 , 0.5276155 , 0.97700177],
       [0.9932144 , 0.99013013, 0.86503178, 0.68683585]])

In [43]:
np.random.randint(1,10)

7

In [44]:
np.random.randn(4,10)

array([[-1.00170991,  1.05111935, -1.10256112, -0.67223145,  1.44462869,
        -0.12288175, -0.30432118,  0.03823247,  0.72095177, -0.05978213],
       [-3.00378168,  0.11480879,  2.39994752,  0.92848994, -0.52115649,
         0.08769638,  1.35134206,  0.46291843,  0.2315067 , -0.95154848],
       [-2.05687162, -1.45881711,  0.78223155,  0.28351935, -0.18983751,
         0.18411031,  0.08782777,  1.1773846 ,  0.34236504, -1.10123291],
       [ 1.13886484, -0.9672029 , -0.34535208,  0.31064796,  0.27198429,
         0.43214301, -0.38765051, -1.27251357, -2.02868139, -0.40337787]])

In [45]:
pd.DataFrame(np.random.randn(4,10))

0         1         2         3         4         5         6  \
0 -1.323972 -0.713714  0.699314 -0.872088 -1.330794  1.788130 -0.465163   
1  0.007379  0.435794  0.349468  0.537953  0.274703 -1.062471  2.102769   
2 -1.000543 -0.781267 -1.840961 -0.240561 -0.277923 -0.520755 -2.107159   
3 -0.350175  0.409588  1.116170  0.889542 -0.140490 -0.441035  0.659769   

          7         8         9  
0 -2.451842 -0.649876  0.069134  
1  0.472398 -1.785964  0.511528  
2 -0.258009 -0.426076  0.134752  
3 -1.660618 -1.477390 -0.522583

In [46]:
a = np.fromfunction((lambda i, j, k: i*j*k), (4,3,2), dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [47]:
print("The array is {}-dimensional".format(a.ndim))
print("The array's shape is {}".format(a.shape))
print("The array has {} elements in itself".format(a.size))

The array is 3-dimensional
The array's shape is (4, 3, 2)
The array has 24 elements in itself


In [48]:
try:
    a.reshape(5,5)
except ValueError as e:
    print('ValueError: {}'.format(e))

ValueError: cannot reshape array of size 24 into shape (5,5)


In [49]:
a.reshape(4,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [50]:
pd.DataFrame(a.reshape(4,6))

0  1  2  3  4  5
0  0  0  0  0  0  0
1  0  0  0  1  0  2
2  0  0  0  2  0  4
3  0  0  0  3  0  6

In [51]:
a.reshape(2,3,2,2)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 1],
         [0, 2]]],


       [[[0, 0],
         [0, 2]],

        [[0, 4],
         [0, 0]],

        [[0, 3],
         [0, 6]]]])

In [52]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [53]:
a.reshape(6,-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [54]:
try:
    a.reshape(5, -1)
except ValueError as e:
    print("ValueError: {}".format(e))

ValueError: cannot reshape array of size 24 into shape (5,newaxis)


In [55]:
a.reshape(4, -777)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [56]:
try:
    a.reshape(4, -1, -1)
except ValueError as e:
    print("ValueError: {}".format(e))

ValueError: can only specify one unknown dimension


In [57]:
list(range(4,10,2))

[4, 6, 8]

##### range generator alternative

In [58]:
try:
    list(range(4,10,0.2))
except TypeError as e:
    print("TypeError: {}".format(e))

TypeError: 'float' object cannot be interpreted as an integer


In [59]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [60]:
a1 = np.arange(4,10,0.2)
a1[1:4]

array([4.2, 4.4, 4.6])

In [61]:
arr = np.random.rand(4,5)
arr

array([[9.13196556e-01, 6.25352550e-02, 2.69336209e-01, 3.23860699e-01,
        9.46104915e-01],
       [2.00764373e-01, 7.75363510e-01, 1.62898773e-01, 8.22150523e-01,
        3.25776707e-01],
       [7.67528256e-01, 7.53864477e-02, 5.77042245e-01, 2.23553737e-01,
        3.48664747e-01],
       [1.65031511e-01, 7.33330093e-04, 6.45045364e-01, 3.88611324e-01,
        1.79486316e-01]])

In [62]:
arr > .5

array([[ True, False, False, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False, False,  True, False, False]])

In [63]:
arr[arr > .5]

array([0.91319656, 0.94610492, 0.77536351, 0.82215052, 0.76752826,
       0.57704224, 0.64504536])

In [64]:
arr[1:3,2]

array([0.16289877, 0.57704224])

In [65]:
arr[[1,2],[2]]

array([0.16289877, 0.57704224])

In [66]:
arr[[1,2],[2]] == arr[1:3,2]

array([ True,  True])

In [67]:
arr = np.random.rand(8,5)
arr

array([[0.85848418, 0.24003698, 0.05225933, 0.0242258 , 0.64387253],
       [0.83586995, 0.10633672, 0.40720416, 0.3768307 , 0.62311573],
       [0.53289296, 0.45217309, 0.67700142, 0.15542554, 0.2702367 ],
       [0.00706153, 0.60815198, 0.1577003 , 0.09889479, 0.18510416],
       [0.14188459, 0.42415441, 0.61411708, 0.45625257, 0.35168341],
       [0.6085257 , 0.41827061, 0.58661141, 0.4149795 , 0.61250625],
       [0.19531266, 0.95196779, 0.41000873, 0.04342406, 0.72504358],
       [0.34932392, 0.36990917, 0.61730604, 0.61703704, 0.16846709]])

In [68]:
arr[1:,:3]

array([[0.83586995, 0.10633672, 0.40720416],
       [0.53289296, 0.45217309, 0.67700142],
       [0.00706153, 0.60815198, 0.1577003 ],
       [0.14188459, 0.42415441, 0.61411708],
       [0.6085257 , 0.41827061, 0.58661141],
       [0.19531266, 0.95196779, 0.41000873],
       [0.34932392, 0.36990917, 0.61730604]])

In [69]:
a2 = arr[1:,:3]
a2

array([[0.83586995, 0.10633672, 0.40720416],
       [0.53289296, 0.45217309, 0.67700142],
       [0.00706153, 0.60815198, 0.1577003 ],
       [0.14188459, 0.42415441, 0.61411708],
       [0.6085257 , 0.41827061, 0.58661141],
       [0.19531266, 0.95196779, 0.41000873],
       [0.34932392, 0.36990917, 0.61730604]])

In [70]:
np.set_printoptions(precision=2, suppress=True)
a2[0][0] = 100
a2

array([[100.  ,   0.11,   0.41],
       [  0.53,   0.45,   0.68],
       [  0.01,   0.61,   0.16],
       [  0.14,   0.42,   0.61],
       [  0.61,   0.42,   0.59],
       [  0.2 ,   0.95,   0.41],
       [  0.35,   0.37,   0.62]])

In [71]:
a2

array([[100.  ,   0.11,   0.41],
       [  0.53,   0.45,   0.68],
       [  0.01,   0.61,   0.16],
       [  0.14,   0.42,   0.61],
       [  0.61,   0.42,   0.59],
       [  0.2 ,   0.95,   0.41],
       [  0.35,   0.37,   0.62]])

In [72]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

In [73]:
a

array([[1, 2],
       [3, 4]])

In [74]:
b

array([[2, 3],
       [4, 5]])

### Element-wise multiplication

In [75]:
a*b

array([[ 2,  6],
       [12, 20]])

In [76]:
a@b

array([[10, 13],
       [22, 29]])

In [77]:
np.mat(a)*np.mat(b)

matrix([[10, 13],
        [22, 29]])

In [78]:
np.mat(a)@np.mat(b)

matrix([[10, 13],
        [22, 29]])

In [79]:
m = np.mat(a)@np.mat(b)
m/0

<ipython-input-79-56e33c5cd871>:2: RuntimeWarning: divide by zero encountered in true_divide
  m/0


matrix([[inf, inf],
        [inf, inf]])