### NumPy

In [1]:
import numpy as np

In [2]:
l = ['aziart',1,2,3,4]
type(l)

list

In [3]:
np.array(l)

array(['aziart', '1', '2', '3', '4'], dtype='<U21')

n-dimensional array

In [4]:
type(np.array(l))

numpy.ndarray

numpy.array tries to upcast its elements. Example:

In [5]:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [6]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
a[1]

array([3, 4])

In [11]:
a[1][1]

4

In [12]:
a[1,1]

4

In [13]:
a1 = np.array([1,2,3,4,5.0])
a1

array([1., 2., 3., 4., 5.])

In [14]:
a1[3]

4.0

In [15]:
np.array([1,2,3,4,5,6], ndmin=0)

array([1, 2, 3, 4, 5, 6])

In [16]:
np.array([1,2,3,4,5,6], ndmin=1)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.array([1,2,3,4,5,6], ndmin=2)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
dim_3 = np.array([1,2,3,4,5,6], ndmin=3)
dim_3

array([[[1, 2, 3, 4, 5, 6]]])

In [24]:
dim_3[0][0][3]

4

In [25]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [26]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [27]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [28]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [29]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [30]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [31]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])