In [1]:
import numpy as np

In [2]:
l = [[1,2],[3,4]]
np.asarray(l)

array([[1, 2],
       [3, 4]])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [9]:
2 * np.ones((3,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [10]:
np.empty((4,5,2))

array([[[3.10503618e+231, 3.10503618e+231],
        [1.08694442e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [3.10503618e+231, 3.10503618e+231],
        [9.38724727e-323, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 2.24729309e+174],
        [3.10503618e+231, 3.10503618e+231],
        [1.48375354e-071, 5.39557895e-062],
        [1.28625693e+248, 4.24948967e-086],
        [1.77290155e+160, 6.86648465e-091]],

       [[3.10503618e+231, 3.10503618e+231],
        [1.16318408e-028, 6.79764291e-310],
        [3.10503618e+231, 3.10503618e+231],
        [2.47032823e-323, 1.03029942e-071],
        [3.11107888e+231, 3.10503618e+231]]])

In [11]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [12]:
np.linspace(2,6,3)

array([2., 4., 6.])

In [13]:
np.linspace(5,100,20)

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [14]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
np.linspace(10,100,10).reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [16]:
np.linspace(10,100,10, endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [17]:
np.linspace(10,100,10, endpoint=False, retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

In [18]:
np.linspace(10,100,10, endpoint=False, retstep=True)[0]

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [19]:
np.linspace(10,100,10, endpoint=False, retstep=True)[1]

9.0

In [20]:
np.logspace(2,3,5, base=10)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [21]:
a = np.arange(2,8)
a

array([2, 3, 4, 5, 6, 7])

In [22]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a.max()

15

In [24]:
a = np.arange(4,20,2).reshape(4,2)
a

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [25]:
a.max()

18

In [26]:
a = np.arange(4,40).reshape(3,6,2)
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [27]:
a.max()

39

In [28]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [29]:
a = np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [30]:
a.max()

39

In [31]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [32]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [33]:
a[3][3]

25

In [34]:
a[3][3]=100

In [35]:
a.max(axis=0)

array([ 34,  35,  36, 100,  38,  39])

In [36]:
a.max(axis=1)

array([  9,  15,  21, 100,  33,  39])

In [37]:
a = np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [38]:
import pandas as pd
pd.DataFrame(a)

0   1   2   3   4   5
0   4   5   6   7   8   9
1  10  11  12  13  14  15
2  16  17  18  19  20  21
3  22  23  24  25  26  27
4  28  29  30  31  32  33
5  34  35  36  37  38  39

In [39]:
20 + a + 10

array([[34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69]])

In [40]:
a/0

<ipython-input-40-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [41]:
2 * a

array([[ 8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [42]:
a ** 2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [43]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [44]:
b = np.array([1,2,3,4,5])

In [45]:
try:
    a+b
except ValueError as e:
    print("ValueError: {}".format(e))

ValueError: operands could not be broadcast together with shapes (6,6) (5,) 


In [46]:
b = np.array([1,10,100,1000,10000,100000])

In [47]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [48]:
a+b

array([[     5,     15,    106,   1007,  10008, 100009],
       [    11,     21,    112,   1013,  10014, 100015],
       [    17,     27,    118,   1019,  10020, 100021],
       [    23,     33,    124,   1025,  10026, 100027],
       [    29,     39,    130,   1031,  10032, 100033],
       [    35,     45,    136,   1037,  10038, 100039]])

In [49]:
a + b.T

array([[     5,     15,    106,   1007,  10008, 100009],
       [    11,     21,    112,   1013,  10014, 100015],
       [    17,     27,    118,   1019,  10020, 100021],
       [    23,     33,    124,   1025,  10026, 100027],
       [    29,     39,    130,   1031,  10032, 100033],
       [    35,     45,    136,   1037,  10038, 100039]])

In [50]:
a + np.invert(b)

array([[     2,     -6,    -95,   -994,  -9993, -99992],
       [     8,      0,    -89,   -988,  -9987, -99986],
       [    14,      6,    -83,   -982,  -9981, -99980],
       [    20,     12,    -77,   -976,  -9975, -99974],
       [    26,     18,    -71,   -970,  -9969, -99968],
       [    32,     24,    -65,   -964,  -9963, -99962]])

In [51]:
a + b.reshape(6,1)

array([[     5,      6,      7,      8,      9,     10],
       [    20,     21,     22,     23,     24,     25],
       [   116,    117,    118,    119,    120,    121],
       [  1022,   1023,   1024,   1025,   1026,   1027],
       [ 10028,  10029,  10030,  10031,  10032,  10033],
       [100034, 100035, 100036, 100037, 100038, 100039]])